---
- name: Bootstrap CloudMan
  hosts: all
  become: yes
  gather_facts: False
  pre_tasks:
    - name: Install Python2 if not available
      vars:
        - ansible_python_interpreter: /usr/bin/python3
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      retries: 30
      delay: 10
    - setup: # aka gather_facts
  tasks:
    - name: Check if Docker is installed
      command: docker
      register: docker_installed
      ignore_errors: True

    - name: Install Docker
      include_role:
        name: docker
      vars:
        docker_users:
          - ubuntu
      when: "docker_installed is failed"

    - name: Install system packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - python-pip
      register: pkg_result
      until: pkg_result is success
      retries: 30
      delay: 10

    - name: Install pip modules
      pip:
        name: ['docker-py']
        state: present

    # Note that this task does not wait for the container to exit/end execution
    - name: Boot CloudMan
      docker_container:
        name: cloudman-boot
        image: "{{ cm_boot_image|default('galaxy/cloudman-boot') }}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        env:
          RANCHER_SERVER: "{{ rancher_server }}"
          RANCHER_PWD: "{{ rancher_pwd|default('Something-To-Change') }}"
          CM_INITIAL_CLUSTER_DATA: "{{ cm_initial_cluster_data|default('', true) }}"
          CM_SKIP_CLOUDMAN: "{{ cm_skip_cloudman|default('false', true) }}"
          KUBE_CLOUD_PROVIDER: "{{ kube_cloud_provider|default('', true) }}"
          KUBE_CLOUD_CONF: "{{ kube_cloud_conf|default('', true) }}"
...
